### ISSUE TITLE
Model Links Dead

### ISSUE THREAD

**Issue by aleph23** [cpmpercussion/creative-prediction#14]
Your model links appear to be dead (checked only MIcroGAN and Doom VAE).  Were they too large to post here?    I briefly looked at your University profile, and it seems you keep busy.  If you don't have time to re-establish a host and update the links on the notebooks, I'd be happy to do both (host models/update links), if you like.  (With the caveat that I will be out of town and not able to until the end of April).

[https://folk.universitetetioslo.no/charlepm/datasets/gan/Xtrain.npy](https://folk.universitetetioslo.no/charlepm/datasets/gan/Xtrain.npy
) yields:

> ## [folk.universitetetioslo.no](https://folk.universitetetioslo.no/)
> ### Personlig nettside ikke funnet
> Beklager, siden du forsøkte å nå finnes ikke.

**Comment by cpmpercussion** [comment]
Hi @aleph23 thanks for the ping! I actually had already rehosted datasets but just not updated every notebook yet. Done now! still some notebooks using older keras imports, etc.

Thanks for your interest!
